# deployment.yml (Versión corregida y final)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      # --- INICIO DE LA SECCIÓN AÑADIDA ---
      # Esto soluciona el error 'Permission denied'
      securityContext:
        fsGroup: 101  # ID del grupo 'odoo'
      # --- FIN DE LA SECCIÓN AÑADIDA ---
      containers:
        - name: odoo
          image: proyectosspr/odoo:v1.4dev
          ports:
            - containerPort: 8069
            - containerPort: 8888
          # La sección 'env' ha sido eliminada para usar solo odoo.conf
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/odoo
            - name: config-volume
              mountPath: /etc/odoo
              readOnly: true
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-data # Asegúrate que tu PVC se llame así
        - name: config-volume
          configMap:
            name: odoo-config # Asegúrate que tu ConfigMap se llame así
            items:
              - key: odoo.conf
                path: odoo.conf